# Generated by Django 4.2.6 on 2023-11-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobspark', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormSubmission',
            new_name='ContactForm',
        ),
    ]
