# Generated by Django 4.2.6 on 2023-11-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobspark', '0007_resume_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_file',
        ),
    ]
