# Generated by Django 4.2.6 on 2023-11-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobspark', '0010_user_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repeat_password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
