# Generated by Django 4.2.6 on 2023-11-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobspark', '0012_user_is_active_user_is_staff_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
